################################################################################################################
# Define Varaibles - CheckRoot Method #
#######################################
CheckRoot_Method="EUID" # Can be wither EUID or UID.  See README_EUIDvsUID.md for more info.
