##################################################################################################################
# Define Variables - Downloader - Advanced #
############################################
BaseURL="https://github.com/tcsresearch"

ExtURL="archive/refs/heads"

FileName="main.zip"
