################################################################################################################
# Define Variables - Dynamic Downloader / Extractor #
#####################################################
# Disabled to prevent issues until implementation is completed.
# ProjectName="$1"
# ZipFile="$2"
# InstallFolder="$3"
