################################################################################################################
# Define Variables - Extractor #
################################
extractor_app="unzip"
extractor_args=" "
