##################################################################################################################
# Define Variables - Install Folders - Base #
#############################################
InstallDir_Base_Root="etc"
InstallDir_Base_NonRoot="$(pwd)"
InstallDir_Base_Selected="None" # This will be changed during runtime based on result of CheckRoot().
# TODO: Need failsafe in case $InstallDir_Base remains as 'None'.

##################################################################################################################
# Define Variables - Install Folders #
######################################
# SelfUpdate #
	TCS_InstallTool_install_Dir="$(pwd)"

# Tmux #
	tmux_install_Dir="/etc"

	tmux_plugins_install_Dir="/etc/tmux/tpm"

# Core Utils #
	BLING_install_Dir="etc/BLING"

	BRCD_install_Dir="/etc/bashrc.d"

	PS1ConfigTool_install_Dir="/etc/PS1ConfigTool"

	ColorEcho_install_Dir="/etc/ColorEcho"

# Repo Utils #
	RepoSync_install_Dir="/etc/RepoSync-ng"

	MirrorMan_install_Dir="/etc/MirrorMan"

# Other Utils #
	TarMonster_install_Dir="/etc/TarMonster"

	AOSPMirrorTool_install_Dir="/etc/AOSPMirrorTool"

  ##################################################################################################################
