################################################################################################################
# Define Varaibles - Version #
##############################
InstallerVersion="0.2.4"
LastModifiedDate="05/01/2026"

################################################################################################################
# Define Varaibles - CheckRoot Method #
#######################################
CheckRoot_Method="EUID" # Can be wither EUID or UID.  See README_EUIDvsUID.md for more info.

################################################################################################################
# Define Variables - Downloaders #
##################################
# Can be aira2 / wget / wget2 / curl

downloader_app="wget"
downloader_args=" -c"

################################################################################################################
# Define Variables - Unzipper #
###############################
extractor_app="unzip"
extractor_args=" "

################################################################################################################
# Define Variables - Dynamic Downloader / Extractor #
#####################################################
# Disabled to prevent issues until implementation is completed.
# ProjectName="$1"
# ZipFile="$2"
# InstallFolder="$3"

################################################################################################################
# Define Variables - Full URLs #
################################
# SelfUpdate #
  SelfUpdate_URL="https://raw.githubusercontent.com/tcsresearch/TCS_InstallTool/refs/heads/main/TCS_InstallTool-v2.sh"

# tmux #
  tmux_install_URL="https://github.com/tcsresearch/tmux-configs/archive/refs/heads/main.zip"

# tmux-custom-plugins #
  tmux_plugins_install_URL="https://github.com/tcsresearch/tmux-custom-plugins/archive/refs/heads/main.zip"

# BLING #
  BLING_install_URL="https://github.com/tcsresearch/BLING/archive/refs/heads/main.zip"

# BRCD #
  BRCD_install_URL="https://github.com/tcsresearch/BRCD/archive/refs/heads/main.zip"

# PS1ConfigTool #
  PS1ConfigTool_install_URL="https://github.com/tcsresearch/PS1ConfigTool/archive/refs/heads/main.zip"

# ColorEcho #
  ColorEcho_install_URL="https://github.com/tcsresearch/ColorEcho/archive/refs/heads/main.zip"

##################################################################################################################
# Define Variables - Advanced #
###############################
BaseURL="https://github.com/tcsresearch"

ExtURL="archive/refs/heads"

FileName="main.zip"


##################################################################################################################
# Define Variables - Install Folders - Base #
#############################################
InstallDir_Base_Root="etc"
InstallDir_Base_NonRoot="$(pwd)"

##################################################################################################################
# Define Variables - Install Folders #
######################################
# SelfUpdate #
	TCS_InstallTool_install_Dir="$(pwd)"

# Tmux #
	tmux_install_Dir="/etc"

	tmux_plugins_install_Dir="/etc/tmux/tpm"

# Core Utils #
	BLING_install_Dir="etc/BLING"

	BRCD_install_Dir="/etc/bashrc.d"

	PS1ConfigTool_install_Dir="/etc/PS1ConfigTool"

	ColorEcho_install_Dir="/etc/ColorEcho"

# Repo Utils #
	RepoSync_install_Dir="/etc/RepoSync-ng"

	MirrorMan_install_Dir="/etc/MirrorMan"

# Other Utils #
	TarMonster_install_Dir="/etc/TarMonster"

	AOSPMirrorTool_install_Dir="/etc/AOSPMirrorTool"

  ##################################################################################################################
