################################################################################################################
# Define Variables - Extractor #
################################
extractor_app="unzip" # Should remain as 'unzip', but should later be configuarble as 'tar', 'bzip2', 'pbzip2', or 'xz'.
extractor_args=" "
