################################################################################################################
# Define Varaibles - Version #
##############################
InstallerVersion="0.2.4"
LastModifiedDate="05/01/2026"

################################################################################################################
# Define Varaibles - CheckRoot Method #
#######################################
CheckRoot_Method="EUID" # Can be wither EUID or UID.  See README_EUIDvsUID.md for more info.

################################################################################################################
# Define Variables - Downloaders #
##################################
# Can be aira2 / wget / wget2 / curl

downloader_app="wget"
downloader_args=" -c"

################################################################################################################
# Define Variables - Unzipper #
###############################
extractor_app="unzip"
extractor_args=" "

################################################################################################################
# Define Variables - Dynamic Downloader / Extractor #
#####################################################
# Disabled to prevent issues until implementation is completed.
# ProjectName="$1"
# ZipFile="$2"
# InstallFolder="$3"
