################################################################################################################
# Define Varaibles - Version #
##############################
InstallerVersion="26.07_r1"
LastModifiedDate="07/02/2026"
