################################################################################################################
# Define Varaibles - Version #
##############################
InstallerVersion="0.2.4"
LastModifiedDate="05/01/2026"
